info:
  contact: {}
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Check Health
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Check Health
      tags:
      - health
swagger: "2.0"
