info:
  contact: {}
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Check Health
      produces:
      - application/json
      responses: {}
      summary: Check Health
      tags:
      - health
swagger: "2.0"
